### ISSUE TITLE
firefox version?

### ISSUE THREAD

**Issue by elliprime** [FactsFromCats/tiktok_celebrity_blocker#5]
I think this extension is only for chrome correct? Are there plans to make a version for firefox? (If not, I am willing to spend some time on that if the code is made available.)

**Comment by FactsFromCats** [comment]
Hello. Thank you for reaching out and offering to contribute to the project. A firefox version should be available in the coming days. I've submitted it to Mozilla and awaiting approval. I'll keep you posted.

**Comment by FactsFromCats** [comment]
Hi @elliprime The Firefox version is now available at https://addons.mozilla.org/en-CA/firefox/addon/blockout/

Please let me know if you have any issues or suggestions.

**Comment by elliprime** [comment]
@FactsFromCats awesome, thanks! I'll close this since it's available for firefox now.
